"""empty message

Revision ID: 5385621d0efb
Revises: f80d49c70d5e
Create Date: 2023-05-17 01:57:30.976803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5385621d0efb'
down_revision = 'f80d49c70d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
