"""empty message

Revision ID: c6a01c76a9bc
Revises: 5385621d0efb
Create Date: 2023-05-17 02:05:02.876337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a01c76a9bc'
down_revision = '5385621d0efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_url', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('img_url', sa.String(length=150), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('img_url')
        batch_op.drop_column('song_url')

    # ### end Alembic commands ###
